Git tutorial
Dev-ES/blog pull request #12
Opened 2018-01-05 02:12 UTC by gabrielreisn

Postagem no blog sobre git e github. Fiz de maneira bem prática e curta para evitar colocar muitas screenshots e tornar a coisa massante. Inclui o básico do dia-a-dia (clone, commit, push) bem como no final alguma coisa sobre como melhor organizar o processo com branch e pull requests em geral.

ps: demorou mas foi!

2018-01-05 03:19 UTC, josmardias requested changes
some text changes requested, some paragraph improvements

a lot of potential here!

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +description: breve tutorial sobre Git e GitHub, suas diferenças bem como funções básicas para todo dev.
```
- breve
+ Breve
```

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +categories: tutoriais
```
- categories: tutoriais
+ categories: git, github
```

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Pensando nisso e em uma maneira melhor de se organizar códigos o Git e o GitHub surgiram pre resolver esses problemas
```
- surgiram pre resolver
+ surgiram para resolver
```

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Primeiramente, se você utiliza Windows deve baixar o [git-bash](https://git-scm.com/download/), se for usuário de linux ou mac, que apesar de normalmente já terem git por padrão, pode-se facilmente i
```
- se for usuário de linux
+ se for usuário de Linux
```

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Primeiramente, se você utiliza Windows deve baixar o [git-bash](https://git-scm.com/download/), se for usuário de linux ou mac, que apesar de normalmente já terem git por padrão, pode-se facilmente i
`pode-se facilmente instalar com sudo apt-get install git`
Essa afirmação só é válida para Ubuntu e similares.

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +   https://github.com/gabrielreisn/git-tutorial.git
Essa "url gerada no final do processo" ficou meio vago.
Tem um botão maneiro para clicar e pegar essa URL.
Acho que seria interessante mostrar aqui :thinking:

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +   git clone
melhor colocar tudo na mesma linha
`git clone https://github.com/gabrielreisn/git-tutorial.git`

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Reparem na imagem acima, no canto direito das linhas destacadas, sempre existe um "(master)" nelas, o que significa que estamos no branch, ou ramificação, principal do nosso repositório e apesar de i
A frase `sempre existe um "(master)" nelas` está esquisita.
Não precisa dizer que "sempre tem", até por que não é totalmente verdade.
Melhor mostrar que na tela que você apresentou está escrito `master`, e explicar o que significa.

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Reparem na imagem acima, no canto direito das linhas destacadas, sempre existe um "(master)" nelas, o que significa que estamos no branch, ou ramificação, principal do nosso repositório e apesar de i
`Reparem na imagem acima, (..) existe um "(master)" nelas, o que significa que estamos no branch, ou ramificação, principal do nosso repositório e (...) quando duas pessoas ou mais alteram a mesma linha de um arquivo.`

Esse parágrafo inteiro está mal formulado.
Começou com objetivo de dizer que "qual branch estamos" mas partiu para para conflito de merge.

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Reparem na imagem acima, no canto direito das linhas destacadas, sempre existe um "(master)" nelas, o que significa que estamos no branch, ou ramificação, principal do nosso repositório e apesar de i
Nesse parágrafo também você tentou inserir a idéia de branchs.
Acho que `branch` é algo central no git, e não deve aparecer em um final de parágrafo e sim ter um tópico mais dedicado, mais intencional, explicando que branchs existem e por que.

---


Bônus:
Acho desnecessário falar sobre `git flow` nesse momento. É um conceito mais para frente e não precisa saber git flow para usar git adequadamente. Aliás, a afirmação de que "git flow" foi criado para resolver ou amenizar conflitos de merge está equivocado. Trabalhar em branchs separados, modularizar o código e usar boas práticas "git friendly" é que tem poder de diminuir incidência de conflitos.

O `git flow` em si é uma arquitetura de branchs que tem muito mais a ver com o ciclo de entrega do software. Para evitar desentendimentos, aconselho deixar esse conceito de fora do escopo desse post.

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Lembrando que é sempre uma boa ideia deixar as coisas o mais claro possível para você e outras pessoas na equipe, seja um commit, um branch ou um PR! Vamos adicionar um readme ao projeto usando uma n
o conceito `PR` não foi introduzido nesse momento do post

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Isso criar um novo branch e automaticamente muda para o mesmo, mas esse branch fica salvo apenas localmente, o que significa que precisamos monitorar esse branch remotamente, assim como nosso reposit
```
- Isso criar um novo branch
+ Esse comando cria um novo branch
```

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Isso criar um novo branch e automaticamente muda para o mesmo, mas esse branch fica salvo apenas localmente, o que significa que precisamos monitorar esse branch remotamente, assim como nosso reposit
`precisamos monitorar esse branch remotamente`
a palavra `monitorar` ficou estranho aqui

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Isso criar um novo branch e automaticamente muda para o mesmo, mas esse branch fica salvo apenas localmente, o que significa que precisamos monitorar esse branch remotamente, assim como nosso reposit
`assim como nosso repositório`
não entendi essa parte da frase

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Todo o processo agora deve seguir como explicado acima, mas ao invés dos commits seguirem para o master eles irão para a nova branch criada, organizando melhor assim as coisas. Ao fim da nova feature
a sigla `PR` ainda é desconhecida nesse ponto

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Com uma fácil e amigável interface, o git torna o processo de pull request bem simples nos projetos, bastando depois apenas documentar brevemente o motivo da requisição do pull request bem como qual
```
- motivo da requisição do pull request
+ motivo do pull request
```

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Com uma fácil e amigável interface, o git torna o processo de pull request bem simples nos projetos, bastando depois apenas documentar brevemente o motivo da requisição do pull request bem como qual
`o git torna`
na verdade é o GitHub

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Com uma fácil e amigável interface, o git torna o processo de pull request bem simples nos projetos, bastando depois apenas documentar brevemente o motivo da requisição do pull request bem como qual
`pull request` foi escrito `Pull Request` no final do texto
tem que adotar algum padrão
recomendo escrever sempre `Pull Request` ou  `PR`
e claro, adicionar o tópico introduzindo oq é um Pull Request, antes de se referir pela primeira vez

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Uma vez aprovado o Pull request, o ciclo começa novamente, puxando sempre um branch novo a partir do master e incorporando ao mesmo ao fim de cada feature nova!
Faltou mostrar a tela do Pull Request, mostrar que existe a questão de aprovar ou pedir correções.
O ciclo não termina com o Pull Request aprovado, e sim com ele `merged`.

2018-01-05 03:19 UTC, josmardias commented on _posts/2017-12-04-tutorial-git.md
> +Uma vez aprovado o Pull request, o ciclo começa novamente, puxando sempre um branch novo a partir do master e incorporando ao mesmo ao fim de cada feature nova!
Senti falta de um parágrafo final com conclusões.
É bom fazer um apanhado geral, se não o leitor fica com a sensação de que o texto acabou do nada.
E ajuda também o leitor a fixar melhor os conceitos lidos anteriormente.

2018-01-05 03:21 UTC, josmardias commented
@gabrielreisn 
This post about Git and GitHub has a lot of potential, and it's something we really misses on this blog.
My request for changes is long and boring, if you have any questions you can ping me here or in the Slack.
Thanks for your contribution!

2018-01-05 07:39 UTC, jvrmaia commented on _posts/2017-12-04-tutorial-git.md
> +categories: tutoriais
coloca só `github` no design não cabe os 2 :sob:

2018-01-05 07:40 UTC, jvrmaia commented on _posts/2017-12-04-tutorial-git.md
> +Primeiramente, se você utiliza Windows deve baixar o [git-bash](https://git-scm.com/download/), se for usuário de linux ou mac, que apesar de normalmente já terem git por padrão, pode-se facilmente i
essa parte de instalação não vejo mtos problemas em redirecionar o usuário p/ a fonte principal q contempla todos os sistemas operacionais

2018-01-05 10:16 UTC, jvrmaia commented on _posts/2017-12-04-tutorial-git.md
> +Pensando nisso e em uma maneira melhor de se organizar códigos o Git e o GitHub surgiram pre resolver esses problemas
Acho que é melhor falar que veio para resolver o problema de controle de versão do Kernel do Linux o git e o Github veio como um serviço para isso. Parece que o Git e Github foram criados para gerenciar projetos de faculdade assim.

2018-01-05 10:22 UTC, jvrmaia requested changes
Adicionei minhas considerações e reforcei as do @josmardias

2018-01-05 12:20 UTC, gabrielreisn commented on _posts/2017-12-04-tutorial-git.md
> +Pensando nisso e em uma maneira melhor de se organizar códigos o Git e o GitHub surgiram pre resolver esses problemas
Eu optei por uma abordagem assim pra parecer uma coisa mais prática pra quem ta começando, acabei fazendo um relato meio pessoal ai porque foi justamente na faculdade que eu conheci git e isso melhorou a forma como eu gerenciava os trabalhos, mas acho a observação bem válida! vou focar em outros pontos e fazer uma junção melhor das coisas

2018-01-06 19:06 UTC, gabrielreisn commented on _posts/2017-12-04-tutorial-git.md
> +description: breve tutorial sobre Git e GitHub, suas diferenças bem como funções básicas para todo dev.
fix'd

2018-01-06 19:06 UTC, gabrielreisn commented on _posts/2017-12-04-tutorial-git.md
> +categories: tutoriais
fix'd

2018-01-06 19:06 UTC, gabrielreisn commented on _posts/2017-12-04-tutorial-git.md
> +Pensando nisso e em uma maneira melhor de se organizar códigos o Git e o GitHub surgiram pre resolver esses problemas
fix'd

2018-01-06 19:07 UTC, gabrielreisn commented on _posts/2017-12-04-tutorial-git.md
> +Primeiramente, se você utiliza Windows deve baixar o [git-bash](https://git-scm.com/download/), se for usuário de linux ou mac, que apesar de normalmente já terem git por padrão, pode-se facilmente i
fix'd

2018-01-06 19:07 UTC, gabrielreisn commented on _posts/2017-12-04-tutorial-git.md
> +   https://github.com/gabrielreisn/git-tutorial.git
fix'd

2018-01-06 19:07 UTC, gabrielreisn commented on _posts/2017-12-04-tutorial-git.md
> +   git clone
fix'd

2018-01-07 01:15 UTC, gabrielreisn commented on _posts/2017-12-04-tutorial-git.md
> +Isso criar um novo branch e automaticamente muda para o mesmo, mas esse branch fica salvo apenas localmente, o que significa que precisamos monitorar esse branch remotamente, assim como nosso reposit
fix'd

2024-05-14 13:25 UTC, closed without merging